spring.application.name=PremierZone
spring.datasource.url=jdbc:postgresql://localhost:5432/PL_Data
spring.datasource.username=yashaswikathota
spring.datasource.password={DBPassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
